.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. liquid_qt test_liquid_qt
clean: FORCE
	$(MAKE) -C .. liquid_qt_clean test_liquid_qt_clean
check: FORCE
	$(MAKE) -C .. test_liquid_qt_check
liquid-qt liquid-qt.exe: FORCE
	 $(MAKE) -C .. liquid_qt
